version: "3.7"

services:
  jenkins:
    image: jenkins-dvd:1.0
    ports:
      - "9090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - infrastructure

networks:
  infrastructure:
    name: ci-infrastructure